GET http://localhost:5098/productos
###
GET http://localhost:5098/productos/1

###
POST http://localhost:5098/productos
Content-Type: application/json

{
  "nombre": "Audifonos",
  "precio": 390.90
}

###
PUT http://localhost:5098/productos/7 
Content-Type: application/json

{
  "name": "Monitor OLED",
  "price": 1500.00
}

###
DELETE http://localhost:5098/productos/6